apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
  # namespace: monitoring
spec:
  storageClassName: "ionos-enterprise-hdd"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi