apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cm
  labels:
    app: grafana
data:
  datasource.yml: |
    apiVersion: 1
    datasources:
     - name: prometheus
       type: prometheus
       access: proxy
       url: http://prometheus-service:8080/
       editable: false
       isDefault: true
       jsonData:
         maxLines: 5000

  grafana.ini: |
    [dataproxy]
    timeout = 600
    [domain]
    read_timeout = 0
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    level = warn
    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
