apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
  # namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:7.5.16
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP

          volumeMounts:
            - name: grafana-pv
              mountPath: /var/lib/grafana
            - name: config
              mountPath: "/etc/grafana/"

          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-password

      volumes:
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: config
          configMap:
            name: grafana-cm
            items:
             - key: grafana.ini
               path: grafana.ini
             - key: datasource.yml
               path: provisioning/datasources/datasource.yml
