apiVersion: v1
kind: Service
metadata:
  name: blackbox-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9115'
spec:
  selector: 
    app: blackbox
  type: ClusterIP  
  ports:
    - port: 9115
      targetPort: 9115 